### ISSUE TITLE
Can't build on Ubuntu 18.04 with clang-15

### ISSUE THREAD

**Issue by mingodad** [neumannt/cppfront-exp#2]
What's the recommended compiler to build this project ?

When trying to build on Ubuntu 18.04 with clang-15 I'm getting this errors:
```
make
[  8%] Built target packcc
Consolidate compiler generated dependencies of target cppfront-exp
[ 13%] Building CXX object CMakeFiles/cppfront-exp.dir/src/parser/Parser.cpp.o
\2 ::= \1cppfront-exp/src/parser/Parser.cpp:25:30: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    errors.emplace_back(loc, move(text));
                             ^
                             std::
In file included from \2 ::= \1cppfront-exp/src/parser/Parser.cpp:1:
In file included from \2 ::= \1cppfront-exp/src/parser/Parser.hpp:8:
In file included from \2 ::= \1cppfront-exp/src/parser/AST.hpp:8:
In file included from \2 ::= \1cppfront-exp/src/parser/Range.hpp:8:
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/string:55:
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/basic_string.h:40:
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/ext/alloc_traits.h:34:
/usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/alloc_traits.h:514:4: error: no matching function for call to 'construct_at'
          std::construct_at(__p, std::forward<_Args>(__args)...);
          ^~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/vector.tcc:115:21: note: in instantiation of function template specialization 'std::allocator_traits<std::allocator<cpp2exp::Error>>::construct<cpp2exp::Error, cpp2exp::SourceLocation &, std::basic_string<char>>' requested here
            _Alloc_traits::construct(this->_M_impl, this->_M_impl._M_finish,
                           ^
\2 ::= \1cppfront-exp/src/parser/Parser.cpp:25:12: note: in instantiation of function template specialization 'std::vector<cpp2exp::Error>::emplace_back<cpp2exp::SourceLocation &, std::basic_string<char>>' requested here
    errors.emplace_back(loc, move(text));
           ^
/usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_construct.h:94:5: note: candidate template ignored: substitution failure [with _Tp = cpp2exp::Error, _Args = <cpp2exp::SourceLocation &, std::basic_string<char>>]: no matching constructor for initialization of 'cpp2exp::Error'
    construct_at(_Tp* __location, _Args&&... __args)
    ^
2 errors generated.
CMakeFiles/cppfront-exp.dir/build.make:139: recipe for target 'CMakeFiles/cppfront-exp.dir/src/parser/Parser.cpp.o' failed
make[2]: *** [CMakeFiles/cppfront-exp.dir/src/parser/Parser.cpp.o] Error 1
CMakeFiles/Makefile2:110: recipe for target 'CMakeFiles/cppfront-exp.dir/all' failed
make[1]: *** [CMakeFiles/cppfront-exp.dir/all] Error 2
Makefile:100: recipe for target 'all' failed
make: *** [all] Error 2
```
Even after fix the missing `std::move` I'm getting this error:
```
make
Consolidate compiler generated dependencies of target packcc
[  8%] Built target packcc
Consolidate compiler generated dependencies of target cppfront-exp
[ 13%] Building CXX object CMakeFiles/cppfront-exp.dir/src/parser/Parser.cpp.o
In file included from \2 ::= \1cppfront-exp/src/parser/Parser.cpp:1:
In file included from \2 ::= \1cppfront-exp/src/parser/Parser.hpp:8:
In file included from \2 ::= \1cppfront-exp/src/parser/AST.hpp:8:
In file included from \2 ::= \1cppfront-exp/src/parser/Range.hpp:8:
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/string:55:
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/basic_string.h:40:
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/ext/alloc_traits.h:34:
/usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/alloc_traits.h:514:4: error: no matching function for call to 'construct_at'
          std::construct_at(__p, std::forward<_Args>(__args)...);
          ^~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/vector.tcc:115:21: note: in instantiation of function template specialization 'std::allocator_traits<std::allocator<cpp2exp::Error>>::construct<cpp2exp::Error, cpp2exp::SourceLocation &, std::basic_string<char>>' requested here
            _Alloc_traits::construct(this->_M_impl, this->_M_impl._M_finish,
                           ^
\2 ::= \1cppfront-exp/src/parser/Parser.cpp:25:12: note: in instantiation of function template specialization 'std::vector<cpp2exp::Error>::emplace_back<cpp2exp::SourceLocation &, std::basic_string<char>>' requested here
    errors.emplace_back(loc, std::move(text));
           ^
/usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_construct.h:94:5: note: candidate template ignored: substitution failure [with _Tp = cpp2exp::Error, _Args = <cpp2exp::SourceLocation &, std::basic_string<char>>]: no matching constructor for initialization of 'cpp2exp::Error'
    construct_at(_Tp* __location, _Args&&... __args)
    ^
1 error generated.
CMakeFiles/cppfront-exp.dir/build.make:139: recipe for target 'CMakeFiles/cppfront-exp.dir/src/parser/Parser.cpp.o' failed
make[2]: *** [CMakeFiles/cppfront-exp.dir/src/parser/Parser.cpp.o] Error 1
CMakeFiles/Makefile2:110: recipe for target 'CMakeFiles/cppfront-exp.dir/all' failed
make[1]: *** [CMakeFiles/cppfront-exp.dir/all] Error 2
Makefile:100: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by neumannt** [comment]
I have only build it with g++ 12 so far, I will take a look...

**Comment by neumannt** [comment]
I have pushed an updated version, it builds with clang 15 now

**Comment by mingodad** [comment]
Thank you !
I can build it now.
